### ISSUE TITLE
How does one get the data

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/TTT4HPC_parallel_workflows#16]
- Iris.pkl isn't in the repo
- I found a link to https://scikit-learn.org/stable/auto_examples/datasets/plot_iris_dataset.html but it doesn't have Iris.pkl
- Can instructions say how to create the data structure where it will be (`data/preprocessed/...`)
- Files, for example in https://coderefinery.github.io/TTT4HPC_parallel_workflows/parallelization/parallelize_using_script/#updating-the-code-for-parallel-execution-and-flexibility , doesn't seem to match my starting point.

**Comment by rkdarst** [comment]
Basically, I'm not sure if by following the steps I can do it.  Probably it is stuff that we can talk through but I would try to make sure we can do it

**Comment by ruokolt** [comment]
The preprocess.py creates the `data/preprocessed/Iris.pkl` file (it loads the original data from sklearn.datasets, preprocesses it, and saves to disk). Or did it not work?

**Comment by rkdarst** [comment]
Ah, I didn't see that.  I'll assume it works.
